services:
  database:
    container_name: f11a-p16-database
    image: mariadb:11
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql

  api:
    container_name: f11a-p16-api
    image: f11adts/coursemapper-api:01ea7b3 # Change to latest
    depends_on:
      - database

  frontend:
    container_name: f11a-p16-frontend
    image: f11adts/coursemapper-frontend:01ea7b3 # Change to latest
    ports:
      - 8080:8080
    depends_on:
      - api