services:
  database:
    container_name: f11a-p16-database
    image: mariadb:11
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - f11a-p16-network
    restart: unless-stopped

  api:
    container_name: f11a-p16-api
    image: f11adts/coursemapper-api:latest
    build: ./api
    environment:
      - PORT=5000
      - MARIADB_HOST=f11a-p16-database
    ports:
      - 5000:5000
    depends_on:
      - database
    networks:
      - f11a-p16-network
    restart: unless-stopped

  frontend:
    container_name: f11a-p16-frontend
    image: f11adts/coursemapper-frontend:latest
    build: ./frontend
    environment:
      - REACT_APP_API_URL=http://f11a-p16-api:5000
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - f11a-p16-network
    restart: unless-stopped

#  webserver:
#    container_name: f11a-p16-webserver
#    image: nginx:alpine
#    build: ./frontend
#    networks:
#      - f11a-p16-network
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - 80:80

networks:
  f11a-p16-network:
    driver: bridge
